server:
  port: 8082

spring:
  data:
    redis:
      host: redis
      port: 6379
      username:
      password:
  cache:
    type: redis
    redis:
      time-to-live: 60000

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
    username:
    password:
    hikari:
      auto-commit: true
      pool-name: product-pool
      maximum-pool-size: 3
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://authorization
  threads:
    virtual:
      enabled: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: io.factorialsystems.msscstore21products.repository

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
